<a href="https://colab.research.google.com/github/purvxi/ds-practice/blob/main/numpy/02_array_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
a2=np.arange(12).reshape(3,4)
a3=np.arange(12).reshape(4,3)

np.dot(a2,a3)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [7]:
np.floor(a3)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [8]:
np.round(a2)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np.ceil(a2)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [10]:
#0->col 1->row
np.prod(a2,axis=0)

array([  0,  45, 120, 231])

In [12]:
np.var(a3,axis=0)

array([11.25, 11.25, 11.25])