<a href="https://colab.research.google.com/github/purvxi/ds-practice/blob/main/numpy/03_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a1=np.arange(6)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)


In [4]:
a1

array([0, 1, 2, 3, 4, 5])

In [5]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [9]:
# indexing 5,1,3,8 in a2
a2[1,1]

np.int64(8)

In [10]:
a2[0,1]

np.int64(1)

In [11]:
a2[0,3]

np.int64(3)

In [12]:
a2[2,0]

np.int64(8)

In [13]:
# indexing 0 in a3
a3[0,0,0]

np.int64(0)

In [14]:
# indexing 5 in a3
a3[1,0,1]

np.int64(5)

In [15]:
#indexing 2 in a3
a3[0,1,0]

np.int64(2)