<a href="https://colab.research.google.com/github/purvxi/ds-practice/blob/main/numpy/04_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.arange(1,26).reshape(5,5)
print (arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#Get [13, 14, 15] from row
arr[2,2:]

array([13, 14, 15])

In [ ]:
#Get [11, 12, 13] from row
arr[2,:3]

array([11, 12, 13])

In [ ]:
#Get every other element: [11, 13, 15]
arr[2,::2]

array([11, 13, 15])

In [ ]:
#Reverse row entirely
arr[2,::-1]

array([15, 14, 13, 12, 11])

In [ ]:
#Get the entire 3rd row (index 2) → [11,12,13,14,15]
arr[2,:]

array([11, 12, 13, 14, 15])

In [ ]:
#Get the entire last column → [5,10,15,20,25]
arr[:,4]

array([ 5, 10, 15, 20, 25])

In [ ]:
#Get the first two rows, all columns
arr[0:2,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#Get just the single value 18
arr[3,2]

np.int64(18)

In [ ]:
#Extract this 2×2 block from the middle:
# [[13,14],[18,19]]
arr[2:4,2:4]

array([[13, 14],
       [18, 19]])

In [ ]:
#Extract the 3×3 block in the bottom-right corner
arr[2:,2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [ ]:
#Get every other row and every other column
arr[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

In [ ]:
#Get the last row using negative indexing
arr[-1]

array([21, 22, 23, 24, 25])

In [ ]:
#Get the last two columns of the last two rows
arr[3:,3:]

array([[19, 20],
       [24, 25]])

In [ ]:
# Reverse the rows only (flip vertically), keeping column order intact
arr[::-1,0:]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [ ]:
#Reverse the entire array (both rows and columns flipped)
arr[0:,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11],
       [20, 19, 18, 17, 16],
       [25, 24, 23, 22, 21]])

In [13]:
sub = arr[0:2, 0:2]
print(sub)
sub[0,0]=999
print(arr[0,0])


[[1 2]
 [6 7]]
999


In [15]:
#iteration
for i in np.nditer(arr):
  print(i)

999
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25


In [19]:
#transpose
#np.transpose(arr)
arr.T

array([[999,   6,  11,  16,  21],
       [  2,   7,  12,  17,  22],
       [  3,   8,  13,  18,  23],
       [  4,   9,  14,  19,  24],
       [  5,  10,  15,  20,  25]])

In [20]:
#ravel : converts to 1D array
arr.ravel()

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25])