<a href="https://colab.research.google.com/github/purvxi/ds-practice/blob/main/numpy/04_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arr = np.array([[ 1,  2,  3,  4,  5],
                 [ 6,  7,  8,  9, 10],
                 [11, 12, 13, 14, 15],
                 [16, 17, 18, 19, 20],
                 [21, 22, 23, 24, 25]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
#Get [13, 14, 15] from row
arr[2:3,2:]

array([[13, 14, 15]])

In [12]:
#Get [11, 12, 13] from row
arr[2:3,:3]

array([[11, 12, 13]])

In [13]:
#Get every other element: [11, 13, 15]
arr[2,::2]

array([11, 13, 15])

In [22]:
#Reverse row entirely
arr[2,::-1]

array([15, 14, 13, 12, 11])

In [23]:
#Get the entire 3rd row (index 2) → [11,12,13,14,15]
arr[2,:]

array([11, 12, 13, 14, 15])

In [24]:
#Get the entire last column → [5,10,15,20,25]
arr[:,4]

array([ 5, 10, 15, 20, 25])

In [25]:
#Get the first two rows, all columns
arr[0:2,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
#Get just the single value 18
arr[3,2]

np.int64(18)

In [30]:
#Extract this 2×2 block from the middle:
# [[13,14],[18,19]]
arr[2:4,2:4]

array([[13, 14],
       [18, 19]])

In [31]:
#Extract the 3×3 block in the bottom-right corner
arr[2:,2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])