<a href="https://colab.research.google.com/github/purvxi/ds-practice/blob/main/numpy/05_stacking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#stacking
import numpy as np
a1=np.arange(12).reshape(2,6)
a1
a2=np.arange(12,24).reshape(2,6)
a2

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [7]:
#horizontal stacking
np.hstack((a1,a2))

array([[ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11, 18, 19, 20, 21, 22, 23]])

In [8]:
np.hstack((a1,a2,a1,a2))

array([[ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17,  0,  1,  2,  3,
         4,  5, 12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11, 18, 19, 20, 21, 22, 23,  6,  7,  8,  9,
        10, 11, 18, 19, 20, 21, 22, 23]])

In [9]:
#vertical stacking
np.vstack((a1,a2))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [10]:
np.vstack((a1,a2,a2,a1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])