<a href="https://colab.research.google.com/github/purvxi/ds-practice/blob/main/numpy/06_fancy_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#fancy indexing to extract the four corner elements as a single 1D array: [0, 4, 20, 24].
a[(0,0,4,4),(0,4,0,4)]

array([ 0,  4, 20, 24])

In [ ]:
a2 = np.arange(24).reshape(6, 4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a2[(0,0,0),(1,2,3)]

array([1, 2, 3])

In [ ]:
a3 = np.random.randint(-10, 11, size=(4, 4))
a3

array([[ 4,  7,  6, -3],
       [-7,  4, -3,  5],
       [ 5,  7,  0,  3],
       [ 2,  7, -2,  2]])

In [24]:
a3[a3>5]=5
a3[a3<0]=0
a3


array([[4, 5, 5, 0],
       [0, 4, 0, 5],
       [5, 5, 0, 3],
       [2, 5, 0, 2]])

In [25]:
a4 = np.random.randint(1, 101, size=(1, 100))
a4

array([[96, 31, 40,  6, 54, 82, 63, 42, 81,  3, 16, 26, 15, 53, 84, 78,
        79, 85, 31, 87, 26, 39, 33, 72, 99, 23, 31, 53,  6, 60, 37, 71,
        46,  7, 58,  4, 60, 83, 52, 11, 69, 99, 28, 57, 52, 37, 31, 10,
        89, 83, 37, 84, 27, 51, 16, 12, 12, 49, 44, 99, 43,  2, 15, 92,
        23, 23, 17, 26,  9, 64, 29, 31, 30, 26, 23, 65, 94,  2, 35,  8,
        69, 62, 99, 50,  7, 19,  2, 41, 24, 27, 70, 68,  9, 20, 51, 36,
        48, 34, 94,  9]])