<a href="https://colab.research.google.com/github/purvxi/ds-practice/blob/main/numpy/fancy_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
#fancy indexing to extract the four corner elements as a single 1D array: [0, 4, 20, 24].
a[(0,0,4,4),(0,4,0,4)]

array([ 0,  4, 20, 24])

In [7]:
a2 = np.arange(24).reshape(6, 4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
a2[(0,0,0),(1,2,3)]

array([1, 2, 3])

In [12]:
a3 = np.random.randint(-10, 11, size=(4, 4))
a3

array([[ 4,  7,  6, -3],
       [-7,  4, -3,  5],
       [ 5,  7,  0,  3],
       [ 2,  7, -2,  2]])